BookManagement: Use Hibernate as the persistence layer to Servlet project ( Create Model, Dao, Servlet for book, author and Category to manage Book)
tototrinh/BookManagement pull request #1
Opened 2019-07-11 10:37 UTC by tototrinh

hi Mr.Hong, I updated my work, Please review! Thank you

2019-07-17 02:42 UTC, hongvo2308 commented on src/net/bookmanagement/dao/AuthorDAO.java
> +        Transaction transaction = null;
Please fix the indent

2019-07-17 02:42 UTC, hongvo2308 commented on src/net/bookmanagement/dao/AuthorDAO.java
> +        Transaction transaction = null;
Please fix the indent

2019-07-17 02:43 UTC, hongvo2308 commented on src/net/bookmanagement/dao/AuthorDAO.java
> +			transaction.commit();
This comment is unnecessary. Please consider removing it

2019-07-17 02:51 UTC, hongvo2308 commented on src/net/bookmanagement/dao/AuthorDAO.java
> +
Be aware of the return null for the `List`. When we use some method like size(), might cause NPE

2019-07-17 02:51 UTC, hongvo2308 commented on src/net/bookmanagement/dao/BookDAO.java
> +        Transaction transaction = null;
Fix the indent

2019-07-17 02:51 UTC, hongvo2308 commented on src/net/bookmanagement/dao/BookDAO.java
> +
BE aware of returning null for the List

2019-07-17 02:51 UTC, hongvo2308 commented on src/net/bookmanagement/dao/CategoryDAO.java
> +        Transaction transaction = null;
Fix the indent

2019-07-17 02:52 UTC, hongvo2308 commented on src/net/bookmanagement/model/Author.java
> +}
Please update the order of the modifications: Public Protected Private

2019-07-17 02:52 UTC, hongvo2308 commented on src/net/bookmanagement/model/Book.java
> +    @JoinTable(name = "author_book_tbl",
Please fix the indent

2019-07-17 02:53 UTC, hongvo2308 commented on src/net/bookmanagement/model/Book.java
> +}
Update the order of the modifications

2019-07-17 02:53 UTC, hongvo2308 commented on src/net/bookmanagement/model/Category.java
> +
Fix the indent

2019-07-17 02:53 UTC, hongvo2308 commented on src/net/bookmanagement/servlet/BookServlet.java
> +    throws ServletException, IOException {
Fix the indent

2019-07-17 02:54 UTC, hongvo2308 commented on src/net/bookmanagement/utils/HibernateUtil.java
> +}
Update the order of the modifications

2019-07-17 02:54 UTC, ces-hongvo requested changes
@tototrinh 
I have left some comments. Please be noted
Thank you

2019-07-22 01:44 UTC, tototrinh commented
@hongvo2308  I edited according to your comment. please check it again!! thank you

2019-07-23 07:15 UTC, hongvo2308 commented on src/net/bookmanagement/servlet/BookServlet.java
> +			if (category == null)
please use the brackets {}

2019-07-23 07:16 UTC, hongvo2308 commented on src/net/bookmanagement/servlet/BookServlet.java
> +		if (category == null)
Please use the brackets {}

2019-07-23 07:17 UTC, ces-hongvo requested changes
@tototrinh 
This PR is fine. Please be noted to use the brackets {} for some condition checking. That might help to read the code better.
Thank you

2019-08-13 09:25 UTC, merged